### ISSUE TITLE
Unhardcode icon

### ISSUE THREAD

**Issue by varlesh** [AyatanaIndicators/ayatana-settings#16]
Will be good use desktop icon from system icon theme:
`Icon=ayatana-settings`

https://github.com/AyatanaIndicators/ayatana-settings/blob/main/data/applications/ayatana-settings.desktop.in#L6

**Comment by tari01** [comment]
Fixed by https://github.com/AyatanaIndicators/ayatana-settings/commit/9fcd1febdb88892ebbc7f4a0ccd8aa9270433298.
