### ISSUE TITLE
How can the order of indicators be changed?

### ISSUE THREAD

**Issue by johnsonmt01** [AyatanaIndicators/ayatana-settings#18]
I'd like to change the order of my indicator icons, specifically switching Sound and Power.  Neither the settings GUI or dconf editor seem to have a method to do this.  Thank you.

**Comment by tari01** [comment]
The only way to do this, I'm afraid,  is to edit the `Position` property in service files in `/usr/share/ayatana/indicators`. Higher values will move an indicator to the right, lower values to the left. A restart will be required after you make your changes.
